import { SaaSSpec, TableDefinition } from '../types/spec';

/**
 * Generates a minimal Express-based serverless handler that exposes
 * basic CRUD routes for every entity in the spec.
 *
 * This is intentionally a string template (no AI) so it is fast and
 * deterministic — the code just needs to exist so Insforge can deploy it.
 */
export function generateApiLayerCode(spec: SaaSSpec): string {
  const routeBlocks = spec.dbSchema.map((table) => buildRouteBlock(table)).join('\n\n');

  return `
// Auto-generated CRUD API for ${spec.name}
// Generated by Tivra Orchestrator

const express = require('express');
const { Pool } = require('pg');

const app = express();
app.use(express.json());

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

// ---------------------------------------------------------------------------
// Auth middleware — validates Bearer JWT signed with AUTH_SECRET.
// All routes below this point require a valid token.
// ---------------------------------------------------------------------------
function requireAuth(req, res, next) {
  const authHeader = req.headers['authorization'] ?? '';
  if (!authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing or malformed Authorization header' });
  }
  const token = authHeader.slice(7);
  try {
    // Simple HS256 verification without a dependency — split and verify signature.
    const [headerB64, payloadB64, sigB64] = token.split('.');
    if (!headerB64 || !payloadB64 || !sigB64) throw new Error('invalid structure');
    const crypto = require('crypto');
    const expected = crypto
      .createHmac('sha256', process.env.AUTH_SECRET)
      .update(headerB64 + '.' + payloadB64)
      .digest('base64url');
    if (expected !== sigB64) throw new Error('invalid signature');
    req.user = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'));
    next();
  } catch (err) {
    return res.status(401).json({ error: 'Invalid token' });
  }
}

app.use(requireAuth);

${routeBlocks}

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(\`API running on port \${PORT}\`));

module.exports = app;
`.trim();
}

function buildRouteBlock(table: TableDefinition): string {
  const { name } = table;
  const cols = table.columns.map((c) => c.name);
  const insertableCols = cols.filter((c) => c !== 'id' && c !== 'createdAt');

  const insertColsSql = insertableCols.map((c) => `"${c}"`).join(', ');
  const insertValsSql = insertableCols.map((_, i) => `$${i + 1}`).join(', ');
  const insertParams = insertableCols.map((c) => `req.body.${c}`).join(', ');

  const updateSetSql = insertableCols
    .map((c, i) => `"${c}" = $${i + 1}`)
    .join(', ');
  const updateParams = insertableCols.map((c) => `req.body.${c}`).join(', ');

  return `
// ── ${name} ──────────────────────────────────────────────────
app.get('/${name}', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM "${name}" ORDER BY "createdAt" DESC');
    res.json(rows);
  } catch (err) { res.status(500).json({ error: String(err) }); }
});

app.get('/${name}/:id', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM "${name}" WHERE id = $1', [req.params.id]);
    if (!rows[0]) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) { res.status(500).json({ error: String(err) }); }
});

app.post('/${name}', async (req, res) => {
  try {
    const { rows } = await pool.query(
      'INSERT INTO "${name}" (id, ${insertColsSql}, "createdAt") VALUES (gen_random_uuid(), ${insertValsSql}, NOW()) RETURNING *',
      [${insertParams}]
    );
    res.status(201).json(rows[0]);
  } catch (err) { res.status(500).json({ error: String(err) }); }
});

app.put('/${name}/:id', async (req, res) => {
  try {
    const { rows } = await pool.query(
      'UPDATE "${name}" SET ${updateSetSql} WHERE id = $${insertableCols.length + 1} RETURNING *',
      [${updateParams}, req.params.id]
    );
    if (!rows[0]) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) { res.status(500).json({ error: String(err) }); }
});

app.delete('/${name}/:id', async (req, res) => {
  try {
    await pool.query('DELETE FROM "${name}" WHERE id = $1', [req.params.id]);
    res.status(204).end();
  } catch (err) { res.status(500).json({ error: String(err) }); }
});
`.trim();
}
